baseURL: https://supriyatskumar.github.io

languageCode: en-us
#title: "John's Blog"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable Google Analytics
#googleAnalytics: UA-122321624-2

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/background.jpg
  # GitHub repo URL of your site
  gitRepo: https://github.com/supriyatskumar/supriyatskumar.github.io
  # Default branch of your Git repo
  gitBranch: source
  # Provide footer configuration.
  newsletter:
    enable: false
footer:
  enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
  template: footer.html
    # Show/hide navigation in the footer. Default is "true".
  navigation:
    enable: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
  contactMe:
    enable: true
    # Show/hide credentials section in the footer. Default is "true".
  credentials:
    enable: true

  newsletter:
    enable: false
    #provider: mailchimp
    #mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e
    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".

    # Show/hide disclaimer notice in the footer. Default is "false".
  disclaimer:
    enable: true
